# Element-wise operation

## 1. The Python way

In [6]:
values = [1,2,3,4,5]
added_values = [x + 5 for x in values]    

print("values: ", values)
print("added_values: ", added_values)

values:  [1, 2, 3, 4, 5]
added_values:  [6, 7, 8, 9, 10]


## 2. The Numpy way

In [1]:
import numpy as np

In [7]:
values = np.array([[1, 2], [3, 4]])
values += 5
print(values)

[[6 7]
 [8 9]]


아래의 코드와 같이 numpy는 function과 연산자의 형태의 element-wise operation을 제공

In [9]:
some_array = np.array([[1, 2], [3, 4], [5, 6]])
x = np.multiply(some_array, 5) 
y = some_array * 5

print("x: ", x)
print("y: ", y)

x:  [[ 5 10]
 [15 20]
 [25 30]]
y:  [[ 5 10]
 [15 20]
 [25 30]]


## 3. Element-wise Matrix Operations

In [11]:
a = np.array([[1,3],[5,7]])
a

array([[1, 3],
       [5, 7]])

In [12]:
b = np.array([[2,4],[6,8]])
b

array([[2, 4],
       [6, 8]])

In [13]:
print(a + b)

[[ 3  7]
 [11 15]]


그냥 * 를 사용하는 경우, element-wise 곱하기를 함. 따라서 덧셈처럼 shape이 같아야함

In [14]:
print(a * b) 

[[ 2 12]
 [30 56]]
