# Numpy Matrix Multiplication

### Numpy는 여러 종류의 matrix multiplication을 제공하기 때문에, 이를 잘 구별하는 것이 중요

## 1. Element-wise Multiplication

In [2]:
import numpy as np
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
n = m * 0.25
n

array([[ 0.25,  0.5 ,  0.75],
       [ 1.  ,  1.25,  1.5 ]])

In [4]:
m * n

array([[ 0.25,  1.  ,  2.25],
       [ 4.  ,  6.25,  9.  ]])

In [5]:
np.multiply(m, n)   # equivalent to m * n

array([[ 0.25,  1.  ,  2.25],
       [ 4.  ,  6.25,  9.  ]])

## 2. Matrix Product

In [6]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
a.shape

(2, 4)

In [8]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
b.shape

(4, 3)

In [10]:
c = np.matmul(a, b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [11]:
c.shape

(2, 3)

## 3. NumPy's dot function

It turns out that the results of dot and matmul are the same if the matrices are two dimensional

In [12]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [13]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [14]:
a.dot(a)

array([[ 7, 10],
       [15, 22]])

In [15]:
np.matmul(a,a)

array([[ 7, 10],
       [15, 22]])