# Transposes in NumPy

## 1. Transpose

In [2]:
import numpy as np
m = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
print(m.T)
print(m.transpose())

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


transpose는 실제로 값을 바꾸는 것이 아니라 인덱스 구조만 변경, 따라서 효율적이지만 값을 수정할 경우 조심해야함

In [6]:
m_t = m.T
m_t[3][1] = 200
print(m_t)
print(m) # 원래의 m의 값도 변경됨

[[  1   5   9]
 [  2   6  10]
 [  3   7  11]
 [  4 200  12]]
[[  1   2   3   4]
 [  5   6   7 200]
 [  9  10  11  12]]


## 2. A real use case

In [7]:
inputs = np.array([[-0.27, 0.45, 0.64, 0.31]])
inputs

array([[-0.27,  0.45,  0.64,  0.31]])

In [9]:
inputs.shape

(1, 4)

In [10]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])
weights

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [11]:
weights.shape

(3, 4)

In [12]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

In [13]:
np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])