# Making a Column Vector

### You see above that sometimes you'll want a column vector, even though by default Numpy arrays work like row vectors. It's possible to get the transpose of an array like so arr.T, but for a 1D array, the transpose will return a row vector. Instead, use arr[:,None] to create a column vector:

In [1]:
import numpy as np

In [3]:
features = np.array([ 0.49671415, -0.1382643 ,  0.64768854])
print(features)

[ 0.49671415 -0.1382643   0.64768854]


In [5]:
print(features[:, None])

[[ 0.49671415]
 [-0.1382643 ]
 [ 0.64768854]]


### 그냥 Transpose하면 그대로 row vector를 내보냄

In [4]:
print(features.T)

[ 0.49671415 -0.1382643   0.64768854]


### Alternatively, you can create arrays with two dimensions. Then, you can use arr.T to get the column vector.

In [6]:
print(np.array(features, ndmin=2))

[[ 0.49671415 -0.1382643   0.64768854]]


In [7]:
print(np.array(features, ndmin=2).T)

[[ 0.49671415]
 [-0.1382643 ]
 [ 0.64768854]]
