# 1. Making a Column Vector

### You see above that sometimes you'll want a column vector, even though by default Numpy arrays work like row vectors. It's possible to get the transpose of an array like so arr.T, but for a 1D array, the transpose will return a row vector. Instead, use arr[:,None] to create a column vector:

In [2]:
import numpy as np

In [3]:
features = np.array([ 0.49671415, -0.1382643 ,  0.64768854])
print(features)

[ 0.49671415 -0.1382643   0.64768854]


In [5]:
print(features[:, None])

[[ 0.49671415]
 [-0.1382643 ]
 [ 0.64768854]]


### 그냥 Transpose하면 그대로 row vector를 내보냄

In [4]:
print(features.T)

[ 0.49671415 -0.1382643   0.64768854]


### Alternatively, you can create arrays with two dimensions. Then, you can use arr.T to get the column vector.

In [6]:
print(np.array(features, ndmin=2))

[[ 0.49671415 -0.1382643   0.64768854]]


In [7]:
print(np.array(features, ndmin=2).T)

[[ 0.49671415]
 [-0.1382643 ]
 [ 0.64768854]]


# 2. Element-wise multiply between row vector and column vector

### shape가 (3, )과 (6, )인 row끼리 곱하면 error가 발생한다.

In [3]:
x = np.array([1, 2, 3])
y = np.array([1, 2, 3, 4, 5, 6])

In [4]:
x * y

ValueError: operands could not be broadcast together with shapes (3,) (6,) 

### 하지만 만약에 (3,)과 (6, 1)을 곱하면 (6, 3)짜리 행렬이 생성됨

In [7]:
y_transpose = y[:, None]
print(y_transpose)
print(y_transpose.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [10]:
result = x * y_transpose
print(result.shape)

(6, 3)
